# version 0.0.1
include: package:lints/recommended.yaml

linter:
  rules:
    constant_identifier_names: false
    file_names: false
    curly_braces_in_flow_control_structures: false
    use_build_context_synchronously: false
    avoid_print: false
    library_prefixes: any