name: tentative_database
description:
version: 0.0.2
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  true_core:
    git:
      url: https://github.com/TrueCollaboration/true_core.dart.git
  json_ex:
    git:
      url: https://github.com/TrueCollaboration/json_ex.dart.git
  logger_ex_common:
    git:
      url: https://github.com/TrueCollaboration/logger_ex_common.dart.git
  logger_ex:
    git:
      url: https://github.com/TrueCollaboration/logger_ex.dart.git

  ientity:
    git:
      url: https://github.com/TrueCollaboration/ientity.dart.git
      ref: new
  itable_ex:
    git:
      url: https://github.com/TrueCollaboration/itable_ex.dart.git
      ref: new

  ientity_serializable:
    git:
      url: https://github.com/TrueCollaboration/ientity_serializable.dart.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

  build_runner: any

dependency_overrides:
  ientity_serializable:
    path:  D:\.dev\projects\github\flutter\packages\ientity_serializable.dart
  # itable_ex:
  #   path:  D:\.dev\projects\github\flutter\packages\itable_ex.dart
